[theme]
base = "dark"
primaryColor = "#ffcc00"
backgroundColor = "#0a0e1a"
secondaryBackgroundColor = "#111827"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
